import Head from "next/head";
import Row from "../components/Row";
import Banner from "../components/Banner";
import Header from "../components/Header";
import requests from "../requests";

import HLSRow from "../components/HLSRow";

import getBingSourceEntries from "../lib/BingSource";
import getLifeTVSourceEntries from "../lib/LiveTVSource"

import enrichAllEntriesWithLinks from "../lib/JustWatchAPI";

export default function Home({
  bingEntries,
  liveTVEntries,
  trending,
  action,
  topRated,
  horror,
  comedy,
  romance,
  documentary,
}) {
  return (
    <div className="">
      <Head>
        <title>Netflix India - Watch TV Shows Online, Watch Movies Online</title>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner entries={ bingEntries } />

      <div className="">
        <HLSRow title="Live TV" entries={liveTVEntries} />
        <Row title="Trending" movies={trending.results} big={true} />
        <Row title="Top rated" movies={topRated.results} />
        <Row title="Action movies" movies={action.results} />
        <Row title="Documentaries" movies={documentary.results} />
        <Row title="Comedy" movies={comedy.results} />
        <Row title="Horror " movies={horror.results} />
        <Row title="Romance" movies={romance.results} />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const [
    trendingRes,
    actionRes,
    netflixRes,
    topRatedRes,
    horrorRes,
    comedyRes,
    romanceRes,
    documentaryRes,
  ] = await Promise.all([
    fetch(`https://api.themoviedb.org/3${requests.fetchTrending}`),
    fetch(`https://api.themoviedb.org/3${requests.fetchActionMovies}`),
    fetch(`https://api.themoviedb.org/3${requests.fetchNetflixOriginals}`),
    fetch(`https://api.themoviedb.org/3${requests.fetchTopRated}`),
    fetch(`https://api.themoviedb.org/3${requests.fetchHorrorMovies}`),
    fetch(`https://api.themoviedb.org/3${requests.fetchComedyMovies}`),
    fetch(`https://api.themoviedb.org/3${requests.fetchRomanceMovies}`),
    fetch(`https://api.themoviedb.org/3${requests.fetchDocumentaries}`),
  ]);

  const [
    bingEntries,
    liveTVEntries,
    trending,
    action,
    netflix,
    topRated,
    horror,
    comedy,
    romance,
    documentary
  ] = await Promise.all([
    getBingSourceEntries(),
    getLifeTVSourceEntries(),
    trendingRes.json(),
    actionRes.json(),
    netflixRes.json(),
    topRatedRes.json(),
    horrorRes.json(),
    comedyRes.json(),
    romanceRes.json(),
    documentaryRes.json(),
  ]);

  enrichAllEntriesWithLinks([trending.results, action.results, netflix.results, 
    topRated.results, horror.results, comedy.results, romance.results, documentary.results]);

  return {
    props: {
      bingEntries,
      liveTVEntries,
      trending,
      action,
      netflix,
      topRated,
      horror,
      comedy,
      romance,
      documentary
    },
  };
}